subtitler updates

diff --git a/subtitler b/subtitler
--- a/subtitler
+++ b/subtitler
@@ -10,28 +10,49 @@ function fatal {
 function macgyver {
 	for f in Mac*.mkv; do
 		echo "### subtitler --extract -i \"$f\""
-		~/downloads/subtitler --extract -i "$f"
+		subtitler --extract -i "$f"
 	done
 }
 
 function extract_subtitles {
+	output_dir="$INPUTFILE_DIR/$INPUTFILENAME_WITHOUT_EXTENSION"
+	output_file="${output_dir}/${INPUTFILE_BASENAME}"
+
 	echo "Extracting subtitles from: $INPUTFILE"
 	file_info=$(ffprobe -hide_banner -of csv "$INPUTFILE" 2>&1) || fatal "Failed to resolve file info usinf ffprobe. Output: \n$file_info"
 	# File will look like: "  Stream #0:2(eng): Subtitle: ass"
 	[ -n "$VERBOSE" ] && echo -e "ffprobe result: \n$file_info"
 	subtitles=$(echo "$file_info" | grep -i stream | grep -i subtitle | grep -v dvd_subtitle | sed -E 's/.*#([0-9]+:[0-9]+)\(([a-z]+)\).*/\1|\2/g')
-	[ -z "$subtitles" ] && fatal "$INPUTFILE does not contain any subtitles."
 
+	if [ -z "$subtitles" ]; then
+		error "$INPUTFILE does not contain any subtitles."
+		[ -z "$IGNORE_NOT_FOUND" ] && fatal
+
+		mkdir -p -v "$output_dir"
+		mv -v "$INPUTFILE" "$output_file"
+		exit 0
+	fi
+	
 	echo -e "Found $(echo "$subtitles" | wc -l) subtitles: \n$subtitles"
-	filename_without_extension=${INPUTFILE_BASENAME%.*}
+	extract_subtitles_to "$subtitles" "$output_dir"
 
-	output_dir="$INPUTFILE_DIR/$filename_without_extension"
+	echo "Extraction complete, removing embedded subtitles."
+
+	echo "Creating new file without subtitles: $output_file"
+	echo "ffmpeg -i \"$INPUTFILE\" -sn -c copy \"$output_file\""
+	ffmpeg -loglevel warning -i "$INPUTFILE" -sn -c copy "$output_file" || fatal "Failed to remove subtitles"
+	rm -v "$INPUTFILE"
+}
+
+function extract_subtitles_to {
+	subtitles=$1
+	output_dir=$2
 	mkdir -p -v "$output_dir"
 
 	for subtitle in $subtitles; do
 		stream=$(echo "$subtitle" | cut -d'|' -f1)
 		lang=$(echo "$subtitle" | cut -d'|' -f2)
-		output_file="$output_dir/${filename_without_extension}.${lang}.srt"
+		output_file="$output_dir/${INPUTFILENAME_WITHOUT_EXTENSION}.${lang}.srt"
 		echo "Extracting $output_file"
 		[ -f "$output_file" ] && fatal "Output file already exists: $output_file"
 
@@ -40,10 +61,10 @@ function extract_subtitles {
 		ffmpeg -loglevel warning -i "$INPUTFILE" -map "$stream" -c srt "$output_file" || fatal "Failed to extract subtitles"
 		scrub_subtitle "$output_file"
 	done
+}
 
-	echo "Extraction complete, removing embedded subtitles."
-
-	output_file="${output_dir}/${INPUTFILE_BASENAME}"
+function remove_subtitles {
+	output_file="${INPUTFILE_DIR}/${INPUTFILE_BASENAME}"
 
 	echo "Creating new file without subtitles: $output_file"
 	echo "ffmpeg -i \"$INPUTFILE\" -sn -c copy \"$output_file\""
@@ -80,6 +101,9 @@ while [ $# -gt 0 ]; do
 			INPUTFILE=$2
 			shift 1
 			;;
+		--ignore-not-found)
+			IGNORE_NOT_FOUND=true
+			;;
 		-v|--verbose)
 			VERBOSE=true
 			;;
@@ -97,6 +121,7 @@ done
 INPUTFILE_DIR=$(cd "$(dirname "$INPUTFILE")" && pwd)
 INPUTFILE_BASENAME=$(basename "$INPUTFILE")
 INPUTFILE="$INPUTFILE_DIR/$INPUTFILE_BASENAME"
+INPUTFILENAME_WITHOUT_EXTENSION=${INPUTFILE_BASENAME%.*}
 
 case $COMMAND in
 	remove)
