Corrected ffmpeg arguments to not remove additional audio streams

diff --git a/subtitler b/subtitler
--- a/subtitler
+++ b/subtitler
@@ -91,8 +91,8 @@ function do_extract {
 	output_file="${OUTPUT_DIR}/${INPUTFILENAME_WITHOUT_EXTENSION}.${OUTPUT_CONTAINER}"
 
 	echo "Creating new file without subtitles: $output_file"
-	echo "ffmpeg -i \"$old_file\" -sn -c copy \"$output_file\""
-	ffmpeg -analyzeduration 100000000 -probesize 100000000 -loglevel warning -i "$old_file" -sn -c copy "$output_file" || fatal "Failed to create new file without subtitles"
+	echo "ffmpeg -i \"$old_file\" -c copy -map 0 -sn \"$output_file\""
+	ffmpeg -analyzeduration 100000000 -probesize 100000000 -loglevel warning -i "$old_file" -c copy -map 0 -sn "$output_file" || fatal "Failed to create new file without subtitles"
 	rm -v "$old_file"
 	echo
 }
@@ -169,8 +169,8 @@ function do_remove {
 	output_file="$INPUTFILE_DIR/${INPUTFILENAME_WITHOUT_EXTENSION}.new.${OUTPUT_CONTAINER}"
 
 	echo "Creating new file without subtitles: $output_file"
-	echo "ffmpeg -i \"$INPUTFILE\" -sn -c copy \"$output_file\""
-	ffmpeg -analyzeduration 100000000 -probesize 100000000 -loglevel warning -i "$INPUTFILE" -sn -c copy "$output_file" || fatal "Failed to remove subtitles"
+	echo "ffmpeg -i \"$INPUTFILE\" -map 0 -c copy -sn \"$output_file\""
+	ffmpeg -analyzeduration 100000000 -probesize 100000000 -loglevel warning -i "$INPUTFILE" -map 0 -c copy -sn "$output_file" || fatal "Failed to remove subtitles"
 	rm -v "$INPUTFILE"
 	mv -v "$output_file" "$INPUTFILE"
 }
